"use client";

/**
 * Sprite browser — fetches /sprites/index.json at runtime and renders
 * thumbnails grouped by category folder. Pixelated rendering preserves
 * crisp pixel art at the 64px display size; click a tile to select it.
 *
 * The index.json file is generated by hand for now (a tiny node script
 * walking web/public/sprites/). When the prebuild pipeline lands, this
 * generation should move to a build script next to build-module-index.mjs.
 *
 * Editor integration — selecting a sprite reveals a side panel with:
 *   - Path display + a Drafted pip when localStorage has a working copy.
 *   - Edit       → opens the PixelEditor inline.
 *   - Copy       → duplicates the sprite to a new filename in the same
 *                  category, landing as a draft.
 *   - Delete     → clears any draft (the on-disk PNG is untouched —
 *                  the browser can't reach the filesystem).
 *   - New Sprite → header-level action that opens a blank canvas at
 *                  the requested path; the author paints + saves.
 */

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { withBasePath } from "@/util/basePath";
import {
  copySpriteDraft,
  discardSpriteDraft,
  hasSpriteDraft,
  listSpriteDrafts,
  loadSpriteDraft,
} from "@/data_model/spriteDraft";
import { PixelEditor } from "./PixelEditor";

interface SpriteIndex {
  _comment?: string;
  categories: Record<string, string[]>;
}

type LoadState =
  | { kind: "loading" }
  | { kind: "ok"; index: SpriteIndex }
  | { kind: "error"; message: string };

/** Mode of the right-hand panel. The browser owns this so the user
 *  can toggle between previewing a sprite and editing one without
 *  re-clicking the list. */
type PanelMode =
  | { kind: "preview"; path: string }
  | { kind: "edit"; path: string; startBlank: boolean };

export function SpriteView() {
  const params = useParams<{ moduleId: string }>();
  const moduleId = params?.moduleId ?? "default";
  const [state, setState] = useState<LoadState>({ kind: "loading" });
  const [panel, setPanel] = useState<PanelMode | null>(null);
  const [filter, setFilter] = useState("");
  /** Set of paths that have drafts. Recomputed whenever the editor
   *  reports a save/discard so the "Drafted" pip stays accurate. */
  const [draftedPaths, setDraftedPaths] = useState<ReadonlySet<string>>(
    () => new Set(),
  );
  /** Bumped on every save / discard / copy / delete so the thumbnail
   *  rendered by the browser refetches the draft. Avoids stale images
   *  without forcing a full reload. */
  const [thumbVersion, setThumbVersion] = useState(0);

  const refreshDrafts = () => {
    setDraftedPaths(new Set(listSpriteDrafts(moduleId)));
    setThumbVersion((v) => v + 1);
  };

  useEffect(() => {
    setState({ kind: "loading" });
    fetch(withBasePath("/sprites/index.json"))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((index: SpriteIndex) => setState({ kind: "ok", index }))
      .catch((e: unknown) =>
        setState({
          kind: "error",
          message: e instanceof Error ? e.message : String(e),
        }),
      );
  }, []);

  useEffect(() => {
    setDraftedPaths(new Set(listSpriteDrafts(moduleId)));
  }, [moduleId]);

  if (state.kind === "loading") {
    return <p className="p-4 text-parchment/60">Loading sprites…</p>;
  }
  if (state.kind === "error") {
    return (
      <div className="p-4">
        <p className="text-ember">Failed to load sprites.</p>
        <p className="mt-2 font-mono text-sm text-parchment/60">
          {state.message}
        </p>
      </div>
    );
  }

  const categories = state.index.categories;
  const total = Object.values(categories).reduce((n, arr) => n + arr.length, 0);
  const needle = filter.trim().toLowerCase();

  return (
    <div className="p-4">
      <header className="flex items-baseline justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl text-parchment">Sprites</h1>
          <p className="mt-1 text-sm text-parchment/60">
            {total} files across {Object.keys(categories).length} categories
            · served from <code className="text-parchment/80">/sprites/</code>
            {draftedPaths.size > 0 ? (
              <span className="ml-2 text-amber-300/80">
                · {draftedPaths.size} drafted
              </span>
            ) : null}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <input
            type="text"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder="filter by name…"
            className="rounded border border-parchment/20 bg-ink/40 px-2 py-1 text-sm text-parchment placeholder:text-parchment/40 focus:border-parchment/60 focus:outline-none"
          />
          <NewSpriteButton
            categories={Object.keys(categories)}
            onCreate={(path) => {
              setPanel({ kind: "edit", path, startBlank: true });
            }}
          />
        </div>
      </header>

      {panel ? (
        <SidePanel
          mode={panel}
          moduleId={moduleId}
          onClose={() => setPanel(null)}
          onEdit={(path) =>
            setPanel({ kind: "edit", path, startBlank: false })
          }
          onCopy={async (fromPath, toPath) => {
            // Pre-resolve the source: existing draft beats the on-disk
            // PNG, but we still need to feed copySpriteDraft a fallback
            // data URL when no draft exists. Fetch + canvas-encode the
            // source PNG so the copy always has bytes to write.
            let sourceDataUrl: string | null = null;
            if (!hasSpriteDraft(moduleId, fromPath)) {
              try {
                const res = await fetch(
                  withBasePath(`/sprites/${fromPath.replace(/^\/+/, "")}`),
                );
                if (res.ok) {
                  const blob = await res.blob();
                  sourceDataUrl = await blobToDataUrl(blob);
                }
              } catch {
                /* fall through with null */
              }
            }
            const ok = copySpriteDraft(
              moduleId,
              fromPath,
              toPath,
              sourceDataUrl,
            );
            if (ok) {
              refreshDrafts();
              setPanel({ kind: "edit", path: toPath, startBlank: false });
            }
          }}
          onDelete={(path) => {
            discardSpriteDraft(moduleId, path);
            refreshDrafts();
            setPanel(null);
          }}
          refreshDrafts={refreshDrafts}
          // Force-rerender the in-panel thumbnail whenever drafts
          // change on the wider page.
          thumbVersion={thumbVersion}
          // Pre-existing draft check for the "Drafted" pip in the
          // panel header — recomputed every render.
          drafted={draftedPaths.has(panel.kind === "preview"
            ? panel.path
            : panel.path)}
        />
      ) : null}

      <div className="mt-6 space-y-6">
        {Object.entries(categories).map(([cat, files]) => {
          const filtered = needle
            ? files.filter((f) => f.toLowerCase().includes(needle))
            : files;
          if (filtered.length === 0) return null;
          return (
            <section key={cat}>
              <h2 className="mb-2 text-xs uppercase tracking-wide text-parchment/40">
                {cat} · {filtered.length}
                {filtered.length !== files.length ? ` of ${files.length}` : ""}
              </h2>
              <ul className="grid grid-cols-[repeat(auto-fill,minmax(90px,1fr))] gap-2">
                {filtered.map((file) => {
                  const path = `${cat}/${file}`;
                  const label = file.replace(/\.png$/, "");
                  const isDrafted = draftedPaths.has(path);
                  return (
                    <li key={file}>
                      <button
                        type="button"
                        onClick={() =>
                          setPanel({ kind: "preview", path })
                        }
                        className={[
                          "flex w-full flex-col items-center gap-1 rounded border p-2 transition",
                          isDrafted
                            ? "border-amber-400/60 bg-amber-900/20 hover:border-amber-300"
                            : "border-parchment/10 bg-ink/40 hover:border-parchment/40 hover:bg-ink/60",
                        ].join(" ")}
                      >
                        <Thumbnail
                          moduleId={moduleId}
                          path={path}
                          version={thumbVersion}
                          alt={label}
                        />
                        <span className="w-full truncate text-center text-xs text-parchment/70">
                          {label}
                        </span>
                      </button>
                    </li>
                  );
                })}
              </ul>
            </section>
          );
        })}
      </div>
    </div>
  );
}

/** Thumbnail that prefers the localStorage draft over the on-disk
 *  PNG so the author sees their edits live in the browser too. The
 *  `version` prop forces a re-evaluation when the parent broadcasts
 *  a draft change. */
function Thumbnail({
  moduleId,
  path,
  version,
  alt,
}: {
  moduleId: string;
  path: string;
  version: number;
  alt: string;
}) {
  const src = useMemo(() => {
    void version; // dep — recompute when bumped
    const draft = loadSpriteDraft(moduleId, path);
    return draft ?? withBasePath(`/sprites/${path}`);
  }, [moduleId, path, version]);
  return (
    <img
      src={src}
      alt={alt}
      width={64}
      height={64}
      style={{ imageRendering: "pixelated" }}
      className="h-16 w-16 object-contain"
    />
  );
}

interface SidePanelProps {
  mode: PanelMode;
  moduleId: string;
  drafted: boolean;
  thumbVersion: number;
  onClose: () => void;
  onEdit: (path: string) => void;
  onCopy: (fromPath: string, toPath: string) => void;
  onDelete: (path: string) => void;
  refreshDrafts: () => void;
}

function SidePanel({
  mode,
  moduleId,
  drafted,
  thumbVersion,
  onClose,
  onEdit,
  onCopy,
  onDelete,
  refreshDrafts,
}: SidePanelProps) {
  if (mode.kind === "edit") {
    return (
      <div className="mt-4 rounded border border-parchment/20 bg-ink/60 p-4">
        <div className="mb-3 flex items-center justify-between">
          <div className="font-display text-lg text-parchment">
            Edit sprite
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded border border-parchment/20 px-3 py-1 text-xs text-parchment/80 hover:bg-ink/40"
          >
            Close
          </button>
        </div>
        <PixelEditor
          moduleId={moduleId}
          path={mode.path}
          startBlank={mode.startBlank}
          onSaved={refreshDrafts}
          onDiscarded={refreshDrafts}
        />
      </div>
    );
  }

  // mode.kind === "preview"
  return (
    <div className="mt-4 flex items-start gap-4 rounded border border-parchment/20 bg-ink/60 p-4">
      <Thumbnail
        moduleId={moduleId}
        path={mode.path}
        version={thumbVersion}
        alt={mode.path}
      />
      <div className="flex-1">
        <div className="text-sm text-parchment/60">Path</div>
        <code className="break-all font-mono text-sm text-parchment">
          /sprites/{mode.path}
        </code>
        {drafted ? (
          <div className="mt-1 text-xs text-amber-300/90">
            Drafted — localStorage copy is shadowing the on-disk PNG.
          </div>
        ) : null}
        <div className="mt-2 text-xs text-parchment/50">
          Use this path in data records (e.g. <code>Monster.sprite</code>,{" "}
          <code>Character.sprite</code>). Apply basePath at fetch time.
        </div>
        <div className="mt-3 flex flex-wrap gap-1.5">
          <button
            type="button"
            onClick={() => onEdit(mode.path)}
            className="rounded border border-amber-300/40 bg-amber-700/30 px-3 py-1 text-sm text-parchment hover:bg-amber-700/50"
          >
            Edit
          </button>
          <CopyButton
            sourcePath={mode.path}
            onCopy={(toPath) => onCopy(mode.path, toPath)}
          />
          <button
            type="button"
            onClick={() => {
              if (
                window.confirm(
                  `Discard the draft for ${mode.path}? The on-disk PNG stays untouched.`,
                )
              ) {
                onDelete(mode.path);
              }
            }}
            className="rounded border border-parchment/20 px-3 py-1 text-sm text-parchment/80 hover:bg-ink/40"
            disabled={!drafted}
            title={drafted ? undefined : "No draft to delete."}
          >
            Delete draft
          </button>
          <button
            type="button"
            onClick={onClose}
            className="rounded border border-parchment/20 px-3 py-1 text-sm text-parchment/80 hover:bg-ink/40"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

/** Copy action — prompts for a new filename within the same category
 *  to keep the editing model simple. Authors can always rename more
 *  flexibly via Edit + Save-As later (mid-tier work). */
function CopyButton({
  sourcePath,
  onCopy,
}: {
  sourcePath: string;
  onCopy: (toPath: string) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => {
        const slash = sourcePath.lastIndexOf("/");
        const dir = slash >= 0 ? sourcePath.slice(0, slash + 1) : "";
        const leaf = slash >= 0 ? sourcePath.slice(slash + 1) : sourcePath;
        const base = leaf.replace(/\.png$/i, "");
        const suggestion = `${dir}${base}_copy.png`;
        const next = window.prompt(
          "Copy to (path under /sprites/):",
          suggestion,
        );
        if (!next) return;
        const normalized = next.endsWith(".png") ? next : `${next}.png`;
        if (normalized === sourcePath) return;
        onCopy(normalized);
      }}
      className="rounded border border-parchment/20 px-3 py-1 text-sm text-parchment/80 hover:bg-ink/40"
    >
      Copy
    </button>
  );
}

/** New-sprite action — prompts for a destination path, then opens the
 *  editor in blank-canvas mode. Defaults to the first known category
 *  so authors can just type a name. */
function NewSpriteButton({
  categories,
  onCreate,
}: {
  categories: string[];
  onCreate: (path: string) => void;
}) {
  const defaultCat = categories[0] ?? "map";
  return (
    <button
      type="button"
      onClick={() => {
        const suggestion = `${defaultCat}/new_sprite.png`;
        const next = window.prompt(
          "New sprite path (under /sprites/):",
          suggestion,
        );
        if (!next) return;
        const normalized = next.endsWith(".png") ? next : `${next}.png`;
        onCreate(normalized);
      }}
      className="rounded border border-emerald-400/40 bg-emerald-700/30 px-3 py-1 text-sm text-parchment hover:bg-emerald-700/50"
    >
      + New sprite
    </button>
  );
}

/** Tiny helper — Blob → data URL via FileReader. Used by the copy
 *  flow to encode an on-disk PNG so the draft module (synchronous,
 *  storage-only) can write it. */
function blobToDataUrl(blob: Blob): Promise<string | null> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = () => {
      const r = reader.result;
      resolve(typeof r === "string" ? r : null);
    };
    reader.onerror = () => resolve(null);
    reader.readAsDataURL(blob);
  });
}
