"use client";

/**
 * Sprite browser — fetches /sprites/index.json at runtime and renders
 * thumbnails grouped by category folder. Pixelated rendering preserves
 * crisp pixel art at the 64px display size; click a tile to enlarge.
 *
 * The index.json file is generated by hand for now (a tiny node script
 * walking web/public/sprites/). When the prebuild pipeline lands, this
 * generation should move to a build script next to build-module-index.mjs.
 */

import { useEffect, useState } from "react";
import { withBasePath } from "@/util/basePath";

interface SpriteIndex {
  _comment?: string;
  categories: Record<string, string[]>;
}

type LoadState =
  | { kind: "loading" }
  | { kind: "ok"; index: SpriteIndex }
  | { kind: "error"; message: string };

export function SpriteView() {
  const [state, setState] = useState<LoadState>({ kind: "loading" });
  const [selected, setSelected] = useState<string | null>(null);
  const [filter, setFilter] = useState("");

  useEffect(() => {
    setState({ kind: "loading" });
    fetch(withBasePath("/sprites/index.json"))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((index: SpriteIndex) => setState({ kind: "ok", index }))
      .catch((e: unknown) =>
        setState({
          kind: "error",
          message: e instanceof Error ? e.message : String(e),
        }),
      );
  }, []);

  if (state.kind === "loading") {
    return <p className="p-4 text-parchment/60">Loading sprites…</p>;
  }
  if (state.kind === "error") {
    return (
      <div className="p-4">
        <p className="text-ember">Failed to load sprites.</p>
        <p className="mt-2 font-mono text-sm text-parchment/60">
          {state.message}
        </p>
      </div>
    );
  }

  const categories = state.index.categories;
  const total = Object.values(categories).reduce((n, arr) => n + arr.length, 0);
  const needle = filter.trim().toLowerCase();

  return (
    <div className="p-4">
      <header className="flex items-baseline justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl text-parchment">Sprites</h1>
          <p className="mt-1 text-sm text-parchment/60">
            {total} files across {Object.keys(categories).length} categories
            · served from <code className="text-parchment/80">/sprites/</code>
          </p>
        </div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder="filter by name…"
          className="rounded border border-parchment/20 bg-ink/40 px-2 py-1 text-sm text-parchment placeholder:text-parchment/40 focus:border-parchment/60 focus:outline-none"
        />
      </header>

      {selected && (
        <SelectedPreview
          path={selected}
          onClose={() => setSelected(null)}
        />
      )}

      <div className="mt-6 space-y-6">
        {Object.entries(categories).map(([cat, files]) => {
          const filtered = needle
            ? files.filter((f) => f.toLowerCase().includes(needle))
            : files;
          if (filtered.length === 0) return null;
          return (
            <section key={cat}>
              <h2 className="mb-2 text-xs uppercase tracking-wide text-parchment/40">
                {cat} · {filtered.length}
                {filtered.length !== files.length ? ` of ${files.length}` : ""}
              </h2>
              <ul className="grid grid-cols-[repeat(auto-fill,minmax(90px,1fr))] gap-2">
                {filtered.map((file) => {
                  const path = `/sprites/${cat}/${file}`;
                  const label = file.replace(/\.png$/, "");
                  return (
                    <li key={file}>
                      <button
                        type="button"
                        onClick={() => setSelected(path)}
                        className="flex w-full flex-col items-center gap-1 rounded border border-parchment/10 bg-ink/40 p-2 transition hover:border-parchment/40 hover:bg-ink/60"
                      >
                        <img
                          src={withBasePath(path)}
                          alt={label}
                          width={64}
                          height={64}
                          style={{ imageRendering: "pixelated" }}
                          className="h-16 w-16 object-contain"
                        />
                        <span className="w-full truncate text-center text-xs text-parchment/70">
                          {label}
                        </span>
                      </button>
                    </li>
                  );
                })}
              </ul>
            </section>
          );
        })}
      </div>
    </div>
  );
}

function SelectedPreview({
  path,
  onClose,
}: {
  path: string;
  onClose: () => void;
}) {
  return (
    <div className="mt-4 flex items-start gap-4 rounded border border-parchment/20 bg-ink/60 p-4">
      <img
        src={withBasePath(path)}
        alt={path}
        width={192}
        height={192}
        style={{ imageRendering: "pixelated" }}
        className="h-48 w-48 object-contain"
      />
      <div className="flex-1">
        <div className="text-sm text-parchment/60">Path</div>
        <code className="break-all font-mono text-sm text-parchment">
          {path}
        </code>
        <div className="mt-3 text-xs text-parchment/50">
          Use this path in data records (e.g. <code>Monster.sprite</code>,{" "}
          <code>Character.sprite</code>). Apply basePath at fetch time.
        </div>
        <button
          type="button"
          onClick={onClose}
          className="mt-3 rounded border border-parchment/20 px-3 py-1 text-xs text-parchment/80 hover:bg-ink/40"
        >
          Close
        </button>
      </div>
    </div>
  );
}
